[package]
name = "mars-core-deps"
version = "1.0.0"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
